# name: nodejs-feature-brand-workflow
# on: 
#   workflow_call: #here someone should call 
#     inputs:
#       project:
#         description: 'project name'
#         required: true
#         type: string
#       component:
#         description: 'component name'
#         required: true
#         type: string
#       environment:
#         description: 'environment name'
#         required: true
#         type: string

 

# jobs:
#   trigger:
#     runs-on: ubuntu-latest # github hosted runners
#     steps:
#       - name: checkout code
#         uses: actions/checkout@v6

#       - name: list of files
#         run: ls -l  


# feature branch

# name: nodejs-feature-brand-workflow
# on: 
#   workflow_call: #here someone should call 
#     inputs:
#       project:
#         description: 'project name'
#         required: true
#         type: string
#       component:
#         description: 'component name'
#         required: true
#         type: string
      
 

# jobs:
#   trigger:
#     runs-on: self-hosted # github hosted runners
#     steps:
#       - name: checkout code
#         uses: actions/checkout@v6

#       - name: list of files
#         run: ls -l  


# read the evrsion

name: nodejs-feature-brand-workflow
on: 
  workflow_call: #here someone should call 
    inputs:
      project:
        description: 'project name'
        required: true
        type: string
      component:
        description: 'component name'
        required: true
        type: string
      
 

jobs:
  trigger:
    runs-on: self-hosted # github hosted runners
    steps:
      - name: checkout code
        uses: actions/checkout@v6

      - name: read package.json version
        id: package_version
        run: |
          APP_VERSION=$(jq -r .version package.json)
          echo "VERSION=$APP_VERSION" >> $GITHUB_ENV
          #also avaialble as an environment variable in this step
          echo "Found version: $VERSION"
 
      - name: check app version
        run: echo "$APP_VERSION"

      - name: install dependencies
        run: npm install

      - name: unit tests
        id: unit-tests
        run: npm test

             
             